# fly.toml file generated for reckless-irc on 2021-06-21T22:47:24-07:00

app = "reckless-irc"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services.script_checks]]
  interval = 10000
  timeout = 1000
  command = "/bin/true"
  restart_limit = 0
